name: Scaffold DevOps Module 3 Terraform Git Repository

on:
  workflow_dispatch:
    inputs:
      workspace-name:
        description: 'Name for the workspace to setup. This should be unique'
        required: true 
        type: string

env:
  ARM_TENANT_ID: '653fcdc1-a3dc-4588-96c4-ef684fc1232b'  
  STORAGE_ACCOUNT: sttfdevopsprimer01

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: tibdex/github-app-token@v1
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}   

    - run: |
        curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            https://api.github.com/orgs/CoreBTS/repos \
            -d '{"name":"devops-primer-amo", "private": false}'
