name: Scaffold DevOps Module 3 Terraform Git Repository

on:
  workflow_dispatch:
    inputs:
      workspace-name:
        description: 'Name for the workspace to setup. This should be unique'
        required: true 
        type: string

env:
  ARM_TENANT_ID: '653fcdc1-a3dc-4588-96c4-ef684fc1232b'  
  STORAGE_ACCOUNT: sttfdevopsprimer01
  CREATE_REPOSITORY_NAME: ${{ format("CoreBTS/{0}", inputs.workspace-name) }}

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
  
    - uses: tibdex/github-app-token@v1
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}   

    - run: |
        curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            https://api.github.com/orgs/CoreBTS/repos \
            -d '{ "name":"${{ inputs.workspace-name }}", "private": true }'

  populate-templates:
    runs-on: ubuntu-latest

    steps:
    - uses: tibdex/github-app-token@v1
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}       

    - uses: actions/checkout@v3
      with:
        repository: ${{ env.CREATE_REPOSITORY_NAME }}
        token: ${{ steps.generate_token.outputs.token }}
        path: new_repo

    - uses: actions/checkout@v3
      with:
        path: templates        


    - run: |
        ls ./templates

    - run: |
        ls ./new_repo          

